In [46]:
import tensorflow as tf
from PIL import Image
import numpy as np
from keras.layers import TFSMLayer

MODEL_PATH = r"D:\Projects\JetScope\models\jetscope-EfficientNetB3-TF-v6\1"
loaded = tf.saved_model.load(MODEL_PATH)
infer = loaded.signatures["serving_default"]
print(infer.structured_outputs)

{'output_0': TensorSpec(shape=(None, 100), dtype=tf.float32, name='output_0')}


In [44]:
def load_image(image_path):
    img = Image.open(image_path).convert("RGB")
    img = img.resize((300, 300))
    img_array = np.array(img) / 255.0
    img_tensor = tf.convert_to_tensor([img_array], dtype=tf.float32)
    return img_tensor

image_path = r"D:\Projects\JetScope\data\sample_tests\F-16_June_2008.jpeg"
image_tensor = load_image(image_path)
print(image_tensor)

tf.Tensor(
[[[[0.87058824 0.78431374 0.67058825]
   [0.8627451  0.78431374 0.6745098 ]
   [0.85882354 0.78431374 0.6745098 ]
   ...
   [0.8117647  0.7921569  0.7529412 ]
   [0.80784315 0.79607844 0.75686276]
   [0.8156863  0.79607844 0.7490196 ]]

  [[0.87058824 0.78431374 0.6627451 ]
   [0.8627451  0.78431374 0.6666667 ]
   [0.85882354 0.78431374 0.6666667 ]
   ...
   [0.83137256 0.7921569  0.74509805]
   [0.83137256 0.79607844 0.74509805]
   [0.83137256 0.7921569  0.74509805]]

  [[0.85882354 0.78431374 0.67058825]
   [0.85882354 0.78431374 0.6666667 ]
   [0.8627451  0.78039217 0.65882355]
   ...
   [0.85490197 0.80784315 0.7529412 ]
   [0.8509804  0.80784315 0.7490196 ]
   [0.84313726 0.8        0.74509805]]

  ...

  [[0.79607844 0.69803923 0.50980395]
   [0.7921569  0.69803923 0.50980395]
   [0.79607844 0.69411767 0.5137255 ]
   ...
   [0.8039216  0.7137255  0.5411765 ]
   [0.8        0.70980394 0.5372549 ]
   [0.8        0.70980394 0.54509807]]

  [[0.79607844 0.69411767 0.513725

In [45]:
predictions = infer(image_tensor)["output_0"]
predicted_class = tf.argmax(predictions, axis=1).numpy()[0]

try:
    with open("labels.txt", "r") as f:
        labels = [line.strip() for line in f.readlines()]
    print(f"Predicted class: {labels[predicted_class]}")
except FileNotFoundError:
    print(f"Predicted class index: {predicted_class}")

InvalidArgumentError: cannot compute __inference_signature_wrapper_476120 as input #0(zero-based) was expected to be a string tensor but is a float tensor [Op:__inference_signature_wrapper_476120]